services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LeadingSystems\MerconisThemeInstallerBundle\Display\Common\Helper\Helper:
    public: true
    autowire: false

  merconis.listener.generate_symlinks_listener:
    class: LeadingSystems\MerconisThemeInstallerBundle\EventListener\GenerateSymlinksListener
    arguments:
      - '%kernel.project_dir%'
      - '@service_container'
      - '@?filesystem'
